spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/300523_m_be_hotel
    username: root
    password: Welcome!1

  jpa:
    show-sql: true
    hibernate:
    ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml




